[package]
name = "dyn-inventory"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.8"
proc-macro2 = "1"
quote = "1"
syn = "2"

[dev-dependencies]
test-case = "3"
trybuild = "1"
inventory = "0.3"
