version: "3"

tasks:
  readme:
    cmds:
      - python scripts/readme.py
      - cargo +nightly fmt
      - cargo test --doc

  clippy:
    cmd: cargo clippy

  pre-commit:
    cmds:
      - task: readme
      - task: clippy
